### ISSUE TITLE
index err

### ISSUE THREAD

**Issue by Alexey-T** [myCrack/cuda_hilite_occurrences#4]
-открыл файл из CudaLint- init.py
-сразу посветилось import (каретка 1:1)
-кликаю на 3:21 после слов 'import cudatext'

~~~
Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_hilite_occurrences/__init__.py", line 39, in on_caret
    current_text = _get_current_text(ed_self) # if not (SEL_ALLOW or CARET_ALLOW): bool(current_text) == False
  File "/home/user/.cudatext/py/cuda_hilite_occurrences/__init__.py", line 167, in _get_current_text
    temp = get_word_under_caret(ed)
  File "/home/user/.cudatext/py/cuda_hilite_occurrences/__init__.py", line 130, in get_word_under_caret
    if x > 0:                 l_char = current_line[x - 1]
IndexError: string index out of range
~~~

**Comment by myCrack** [comment]
Исправил.
